package Cap11;

//Figura 11.6:  UsandoExcessoes2.java --> traduÁ„o do ingles UsingException.java
//Desempilhamento.

public  class UsandoExcessoes2
{
    public static void main(String[] args)
    {
        try //chama throwException para demonstrar o desempilhamento
        {
            throwException(); //chama m√©todo throwException
        }//fim de try
        catch (Exception exception) //exceÁ„o lancada em throwException
        {
            System.err.println("Exce√ß√£o tratada no principal");
        }//fim do catch
   }//fim de main

    //throwException lan√ßa exce√ß√£o que n√£o √© capturada nesse m√©todo
    public static void throwException() throws Exception
    {
        try //lan√ßa uma exce√ß√£o e captura em main
        {
            System.out.println("M√©todo throwException");
            throw new Exception();  //gera a excecao
        }//fim de try
        catch (RuntimeException runtimeException) //captura o tipo correto
        {
            System.err.println("Exce√ß√£o tratada no m√©todo lan√ßar Exception");
        }//fim do catch
        finally //o bloco finally sempre executa
        {
            System.err.println("Finalmente √© sempre executado");
        }//fim de finally
   }//fim do metodo throwException
}//fim da classe UsandoExcessoes2